### ISSUE TITLE
_issueNewId() returns -Infinity

### ISSUE THREAD

**Issue by danylevskyi** [rakeshpai/mysensors-controller#4]
Just plugged in new sensor node and found out that `_issueNewId()` returns  `-Infinity`.
### Debug log:

```
Initialized successfully with ../node_modules/mysensors-controller/nodes.json
Connected to ethernet gateway at 192.168.1.66:5003
[MYSC] [4/9/2016, 7:14:30 AM] <- 255;255;3;0;3;
[MYSC] [4/9/2016, 7:14:30 AM] -> 255;255;3;0;1;-Infinity
```
### nodes.json

```
[
  {
    "id": 1,
    "sensors": [
      {
        "id": 0,
        "type": 23,
        "value": 49,
        "updateTime": 1456509303277
      }
    ],
    "protocol": "1.5.4",
    "sketchName": "Light Sensor",
    "sketchVersion": "1.0"
  }
]
```

**Comment by rakeshpai** [comment]
This is strange. Shouldn't happen. Could you please dig a little deeper and tell me what you see? [This line](https://github.com/rakeshpai/mysensors-controller/blob/master/Controller.js#L112) has to be the culprit, but with your `.nodes`, type-casting shouldn't be the issue, since `.id` is numeric and `Math.max` should work on number types. By any chance, is `.id` a string? That's the only thing that comes to mind that could cause this issue.
